## protocol:jdbcdriver://specific-service-name-to-look-for:port-to-find/db_schema
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/rememberthis_db
    username: user
    password: "12345"

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://rememberthis.local/login/oauth2/code/google