## protocol:jdbcdriver://specific-service-name-to-look-for:port-to-find/db_schema
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/rememberthis_db

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://remember-this-app.app/login/oauth2/code/google