## protocol:jdbcdriver://specific-service-name-to-look-for:port-to-find/db_schema
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/rememberthis_db
    username: root
    password: 123Cobblestone!

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google